blueprint:
  name: Notify When Entity is Below Threshold
  description: Sends a notification when an entity's numeric state falls below a specified threshold.
  domain: automation
  input:
    target_entity:
      name: Entity to Monitor
      description: The entity whose numeric state will be monitored.
      selector:
        entity:
          domain: sensor

    notify_service:
      name: Notification Service
      description: The name of the notification service (e.g., `notify.mobile_app_your_phone`).
      selector:
        text:

    threshold:
      name: Threshold Value
      description: Specify the threshold value for the entity. Default is 2.
      default: 2
      selector:
        number:
          min: 0
          max: 100
          step: 0.1

    notification_title:
      name: Notification Title
      description: The title of the notification message.
      default: "Threshold Alert!"
      selector:
        text:

    notification_message:
      name: Notification Message
      description: The body of the notification message. You can use placeholders like `{{ entity_name }}`, `{{ entity_id }}`, and `{{ state }}`.
      default: "The value of {{ entity_name }} has dropped below the threshold. Current value: {{ state }}."
      selector:
        text:

trigger:
  - platform: numeric_state
    entity_id: !input target_entity
    below: !input threshold

action:
  - service: !input notify_service
    data:
      title: !input notification_title
      message: >
        {% set entity_id = trigger.entity_id %}
        {% set entity_name = states[entity_id].name %}
        {% set state = states[entity_id].state %}
        {{ (!input.notification_message)
          | replace('{{ entity_name }}', entity_name)
          | replace('{{ entity_id }}', entity_id)
          | replace('{{ state }}', state) }}

mode: single
