blueprint:
  name: Notify When Entity is Below Threshold
  description: Notify when a selected entity's state falls below a defined threshold value.
  domain: automation
  input:
    target_entity:
      name: Entity to Monitor
      description: Choose the sensor/entity whose state you want to monitor.
      selector:
        entity:
          domain: sensor

    threshold_value:
      name: Threshold Value
      description: Notify when the entity falls below this numeric value.
      default: 2
      selector:
        number:
          min: 0
          max: 100
          step: 1

    notify_device:
      name: Devices to Notify (Mobile App)
      description: Select one or more devices to receive the notification.
      default: []
      selector:
        device:
          filter:
            integration: mobile_app
          multiple: true

    notification_title:
      name: Notification Title
      description: Title of the notification.
      default: "Threshold Alert!"
      selector:
        text

    notification_message:
      name: Notification Message
      description: Message to include in the notification. You can use placeholders such as `{{ entity_name }}` and `{{ state }}`.
      default: "The value of {{ entity_name }} is now {{ state }}."
      selector:
        text

mode: restart

variables:
  entity_id: !input target_entity
  threshold: !input threshold_value
  notify_title: !input notification_title
  notify_message: !input notification_message
  notify_device: !input notify_device

trigger:
  - platform: numeric_state
    entity_id: !input target_entity
    below: !input threshold_value

action:
  - alias: Notify mobile devices
    repeat:
      for_each: !input notify_device
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: !input notification_title
            message: >
              {% set entity_name = states[entity_id].name %}
              {% set state = states[entity_id].state %}
              {{ notify_message | replace('{{ entity_name }}', entity_name) | replace('{{ state }}', state) }}
